version: "3.7"

services:

  dash-board:
    container_name: dash-board
    restart: always
    network_mode: "bridge"        
#    networks:
#      kafka_lan:
#        aliases:
#          - dash-board
    build:
      context: ./build/dash-board
    ports:
      - "8189:8189"

#################################################
# Network initialized by zookeeper and used by
# the whole "kafka-ecosystem": zookeeper,
# kafka, (+ schema-registry & connect when needed
#################################################
# networks:
#   kafka_lan:
#     external:
#       name: docker-kafka-single_kafka_lan
